libreries: 
  - pandas
  - numpy
  - scikit-learn
  - seaborn
  - matplotlib
  - pickle

model:
  name: RandomForestClassifier
  random_state: 11

features:
  - MMSE
  - FunctionalAssessment
  - MemoryComplaints
  - BehavioralProblems
  - ADL

target: Diagnosis

grid_search:
  scoring: recall
  cv: 3
  n_jobs: -1

hyperparameters:
  n_estimators:
    - 400
    - 700
    - 800
  max_depth:
    - 4
    - 5
    - 6
